
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rscombd
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_tripid = new javax.swing.JTextField();
        jTextField_license = new javax.swing.JTextField();
        jComboBox_travelclass = new javax.swing.JComboBox<>();
        jTextField_price = new javax.swing.JTextField();
        jTextField_from = new javax.swing.JTextField();
        jTextField_tlocation = new javax.swing.JTextField();
        jTextField_ttime = new javax.swing.JTextField();
        jTextField_estimate = new javax.swing.JTextField();
        jTextField_to = new javax.swing.JTextField();
        jDateChooser_date = new com.toedter.calendar.JDateChooser();
        jButton_license = new javax.swing.JButton();
        jButton_class = new javax.swing.JButton();
        jButton_price = new javax.swing.JButton();
        jButton_from = new javax.swing.JButton();
        jButton_date = new javax.swing.JButton();
        jButton_location = new javax.swing.JButton();
        jButton_time = new javax.swing.JButton();
        jButton_totaltime = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update info ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(102, 102, 255))); // NOI18N

        jLabel1.setText("Tripd ID");

        jLabel2.setText("Airplane License no");

        jLabel3.setText("Travel class");

        jLabel4.setText("Ticket price");

        jLabel5.setText("From");

        jLabel6.setText("Date");

        jLabel7.setText("Transit Location");

        jLabel8.setText("Transit Time");

        jLabel9.setText("Estimated Travel time");

        jLabel10.setText("To");

        jTextField_tripid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_tripidActionPerformed(evt);
            }
        });

        jComboBox_travelclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Class", "Business Class", "Economy Class" }));
        jComboBox_travelclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_travelclassActionPerformed(evt);
            }
        });

        jButton_license.setText("Update license no");
        jButton_license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_licenseActionPerformed(evt);
            }
        });

        jButton_class.setText("Update Travel class");
        jButton_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_classActionPerformed(evt);
            }
        });

        jButton_price.setText("Edit price");
        jButton_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_priceActionPerformed(evt);
            }
        });

        jButton_from.setText("Edit arrival and destination");
        jButton_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fromActionPerformed(evt);
            }
        });

        jButton_date.setText("Update date");
        jButton_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dateActionPerformed(evt);
            }
        });

        jButton_location.setText("Update location");
        jButton_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_locationActionPerformed(evt);
            }
        });

        jButton_time.setText("Update time");
        jButton_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timeActionPerformed(evt);
            }
        });

        jButton_totaltime.setText("Update total time");
        jButton_totaltime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_totaltimeActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(8, 8, 8)))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_from)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField_ttime)
                                        .addComponent(jTextField_tlocation, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_from)
                                        .addComponent(jTextField_price, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboBox_travelclass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField_license)
                                                .addComponent(jTextField_tripid)))
                                        .addComponent(jTextField_estimate)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_to, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_class)
                                            .addComponent(jButton_license)
                                            .addComponent(jButton_price))
                                        .addGap(52, 52, 52))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_time)
                                            .addComponent(jButton_location)
                                            .addComponent(jButton_totaltime)
                                            .addComponent(jButton_date))
                                        .addContainerGap(25, Short.MAX_VALUE))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_tripid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_license, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_license))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox_travelclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_class))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_price))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_from)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jDateChooser_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_date))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_tlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_location))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_ttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_time))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_estimate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton_totaltime))
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_tripidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_tripidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_tripidActionPerformed

    private void jComboBox_travelclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_travelclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_travelclassActionPerformed
             public boolean checkTrip(String username)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkTrip = false;
        String query = "SELECT * FROM `trip` WHERE `trip_id` =?";
        
        try {
            ps = connect.getConnection().prepareStatement(query);
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkTrip = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Insert.class.getName()).log(Level.SEVERE, null, ex);
        }
         return checkTrip;
    }
    private void jButton_licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_licenseActionPerformed
        // TODO add your handling code here:
        String tripid = jTextField_tripid.getText();
        String license = jTextField_license.getText();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `A_lic` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,license);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The license no has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }//GEN-LAST:event_jButton_licenseActionPerformed
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }
    private void jButton_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_classActionPerformed
        // TODO add your handling code here:
        String tripid = jTextField_tripid.getText();
        String travelclass  = jComboBox_travelclass.getSelectedItem().toString();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `travel_class` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,travelclass);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The travel has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }//GEN-LAST:event_jButton_classActionPerformed

    private void jButton_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_priceActionPerformed
        // TODO add your handling code here:
         String tripid = jTextField_tripid.getText();
         String price =jTextField_price.getText();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `price` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,price);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The price has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }//GEN-LAST:event_jButton_priceActionPerformed

    private void jButton_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_locationActionPerformed
        // TODO add your handling code here:
        String tripid = jTextField_tripid.getText();
        String tlocation =jTextField_tlocation.getText();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `transit_location` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,tlocation);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The transit location has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }//GEN-LAST:event_jButton_locationActionPerformed

    private void jButton_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timeActionPerformed
        // TODO add your handling code here:
        String tripid = jTextField_tripid.getText();
        String ttime =jTextField_ttime.getText();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `transit_time` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,ttime);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The transit time has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }//GEN-LAST:event_jButton_timeActionPerformed

    private void jButton_totaltimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_totaltimeActionPerformed
        // TODO add your handling code here:
        String tripid = jTextField_tripid.getText();
        String estimate =jTextField_estimate.getText();
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `estimated_traveltime` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,estimate);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The transit time has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
                                               
        
    }//GEN-LAST:event_jButton_totaltimeActionPerformed

    private void jButton_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dateActionPerformed
        // TODO add your handling code here:
        String tripid = jTextField_tripid.getText();
        String tdate = null;
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
           if(jDateChooser_date.getDate() != null)
        {
            SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
            tdate = dateformat.format(jDateChooser_date.getDate());
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `departure_date` =? WHERE `trip_id` =?";
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,tdate);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The departure date has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
                                               
        
         
    }//GEN-LAST:event_jButton_dateActionPerformed

    private void jButton_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fromActionPerformed
        // TODO add your handling code here:
        String tripid = jTextField_tripid.getText();
        String from = jTextField_from.getText();
        String to = jTextField_to.getText();
        
        
         if(tripid.equals(""))
        {
          JOptionPane.showMessageDialog(null,"The trip id is compulsory"); 
        }
         
            if(checkTrip(tripid))
            {
        PreparedStatement ps;
        ResultSet rs;
        String query = "UPDATE `trip` SET `departure_location` =? WHERE `trip_id` =?";
        String query1 = "UPDATE `trip` SET `arrival_location` =? WHERE `trip_id` =?";
          
          
             
        
        try {
            ps = connect.getConnection().prepareStatement(query);
             ps.setString(1,from);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
             ps = connect.getConnection().prepareStatement(query1);
             ps.setString(1,to);
             ps.setString(2,tripid);
             ps.executeUpdate();
             
             
             
                     if(ps.executeUpdate()>0)
            {
                JOptionPane.showMessageDialog(null,"The locations has been updated");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }                                               
            else {
                 JOptionPane.showMessageDialog(null,"The trip id is incorrect");
            }
    }//GEN-LAST:event_jButton_fromActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home rgf = new Home();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        //rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
        
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_class;
    private javax.swing.JButton jButton_date;
    private javax.swing.JButton jButton_from;
    private javax.swing.JButton jButton_license;
    private javax.swing.JButton jButton_location;
    private javax.swing.JButton jButton_price;
    private javax.swing.JButton jButton_time;
    private javax.swing.JButton jButton_totaltime;
    private javax.swing.JComboBox<String> jComboBox_travelclass;
    private com.toedter.calendar.JDateChooser jDateChooser_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_estimate;
    private javax.swing.JTextField jTextField_from;
    private javax.swing.JTextField jTextField_license;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextField_tlocation;
    private javax.swing.JTextField jTextField_to;
    private javax.swing.JTextField jTextField_tripid;
    private javax.swing.JTextField jTextField_ttime;
    // End of variables declaration//GEN-END:variables
}
